### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by ComputerScientist-01** [vvHacker007/Mind-Space#18]
1. On the profile page , once we wish to discard our changes the url we are redirected to is 
`http://127.0.0.1:5000/username/profile/` instead of `https://mindspace.cf/username/profile/`

2. This issue also exists when I wish to discard my blog.

![Screenshot from 2021-06-22 18-17-56](https://user-images.githubusercontent.com/39644109/122927142-34cf2080-d386-11eb-89b1-8080a9e1a71f.png)

**Comment by ComputerScientist-01** [comment]
3. when I have discarded the changes on my profile, I get **your blog has been discarded** message instead of your profile changes have been discarded.
![Screenshot from 2021-06-22 18-25-49](https://user-images.githubusercontent.com/39644109/122928472-87f5a300-d387-11eb-8ec6-22e2bfd97d36.png)

**Comment by vvHacker007** [comment]
Thanks a lot @ComputerScientist-01 for noticing and bringing in light the Issues. I have made the fix and updated the website. Do let me know of any other issues if you face them.
